### PR TITLE
Move babel-runtime to peerDependencies

### LINKED ISSUE #72: Specify babel-runtime as a dependency or a peer dependency
Since 0.2.x it seems this depends on the `babel-runtime` module being available at runtime. Should it be moved to the regular dependencies or even the peer dependencies in the package.json?

### PR DESCRIPTION
**Pull request by AsaAyers**
Fixes #72 

I'm just tired of email notifications on this, so I used github's editor to just fix it.

### CODE REVIEW

**Comment by mathieumg** [comment]
Title of the PR is misleading, but change is the right one. :+1:

**Comment by AsaAyers** [comment]
oops. I fixed it :)

**Comment by AsaAyers** [comment]
IDK what the right fix is here. If I move it to `peerDependencies` it seems like it should fix #72, but by moving it, it now doesn't get installed when TravisCI runs the tests. I don't think `peerDependencies` and `devDepenencies` is a good idea, it has to be maintained in 2 places.

**Comment by mathieumg** [comment]
> I don't think peerDependencies and devDepenencies

Oh I never meant both, I only questioned which it should be. It certainly can't be a dev dependency, it has to be either a regular dependency (needed at runtime) or a peer dependency (has to be provided by the users of react-a11y).

In the former case a single instance can be achieved in Webpack/Browserify by deduping, in the latter it  will already leverage the single available instance of the Babel runtime.

**Comment by AsaAyers** [comment]
So the problem with relying on deduping is lets say `react-a11y` depends on version 5, but I have a project where I'm trying out a newer version 6. NPM sees that these can't be de-duped and so it happily installs the two different versions. Now your project won't package correct to be run in the browser. And if somehow it does package correctly, you're now shipping 2 runtimes to the client and you don't want that in the browser either.

Anything that causes the two to not be able to be deduped is going to result in 2 versions in your `node_modules` but browserify will only package one of them to run in the browser.

**Comment by mathieumg** [comment]
See https://github.com/rackt/react-a11y/issues/72#issuecomment-113920891 I imagine that would cover that situation as well?

**Comment by wyattdanger** [comment]
Closed with https://github.com/reactjs/react-a11y/pull/113

**Pull request closed without merging**
