### PR TITLE
Resolve issue 102 by testing both component and its instance

### PR DESCRIPTION
**Pull request by mrfr0g**
This should resolve issue-102 https://github.com/rackt/react-a11y/issues/102

### CODE REVIEW

**Comment by DanielHeath** [comment]
+1, this is the only thing blocking me from getting my team to use react-a11y

**Comment by mrfr0g** [comment]
@DanielHeath are you using a similar sortable solution? If so a workaround that works for me is to wrap the cancel and setState calls into a setTimeout. 


````
setTimeout(function() {
$( ".selector" ).sortable( "cancel" );
this.setState({
   newOrder: ...
});
}.bind(this),10)
````

**Comment by DanielHeath** [comment]
TBH I have no idea what's causing it

**Comment by SimenB** [comment]
@wyattdanger Any chance you could take a look at this? We have to exclude `includeSrcNode: true`, otherwise it throws. This change "fixes" it, in that it makes the warning go away

**Comment by wyattdanger** [comment]
Seems reasonable to me

**Comment by SimenB** [comment]
Sweet, thanks!

**Pull request merged**
