### PR TITLE
Revamp the API and configuration to allow for more modular rules to be added

### PR DESCRIPTION
**Pull request by romeovs**
This doesn't really fix anything, but at least it alleviates the problems in #77, $79 and #85, reducing their scope to the case where the `includeSrcNode` option is set to `true`.

It could be used as a quick fix before #54 or #55 get implemented. It does not change the external API as far as I can tell.

### CODE REVIEW

**Comment by wyattdanger** [comment]
Wow! Huge diff for review. Is the PR title still accurate?

**Comment by wyattdanger** [comment]
@romeovs looks like we have some merge conflicts to resolve but this looks amazing. You think it's sem-ver minor?

**Comment by romeovs** [comment]
The title is not accurate anymore. It could be more along the lines of:
> Revamp the API and configuration and refactor to allow for more modular rules to be added

The PR probably started out as moderate as fixing the includeSourceNode issue, but I was having fun expanding the codebase.

It's semver major for, sure since the configuration changed quite a bit.

Note that I'm currently not actively maintaining this branch anymore, but @erin-doyle and his team kindly volunteered pick up (only just last week) and they're doing a great job at getting this thing more production ready.

I can explain the motivations behind some of the changes I've made if you want.

**Comment by magestican** [comment]
can you guys merge this ?

**Comment by erin-doyle** [comment]
If I can be provided with write access I will be happy to resolve the conflicts and merge.

**Comment by wyattdanger** [comment]
@erin-doyle do you have the access you need?

**Comment by erin-doyle** [comment]
I believe I should.  Thanks @wyattdanger !  I'll try to get this done today!

**Comment by erin-doyle** [comment]
Well the build is failing for a reason not immediately clear to me.  I wonder if it's due at all to the really old version of node being used?  I'm working on trying that version locally to see what I get.

**Comment by erin-doyle** [comment]
I'm having issues with nvm so I haven't tried various versions locally to see how it impacts the build but I would suggest raising the node version being installed by Travis.  I'm not sure 0.10 makes sense to use at this point.

**Comment by wyattdanger** [comment]
We ought to set up a build matrix with several versions

**Comment by erin-doyle** [comment]
Ugh sorry that this added a ton of "new" commits, I did a rebase onto this repo's master in order to resolve the conflicts.  

Also, I added an update to the `.travis.yml` file to replace that old version of node it was building against with a matrix of newer versions.  Unfortunately though it's still failing on node 4 😿 .  I'll keep plugging away at it and hopefully we can get this merged shortly!

**Comment by erin-doyle** [comment]
Ok fixed!  Any chance we can get this merged and put out a v1.0.0?

**Comment by erin-doyle** [comment]
@wyattdanger I know you're busy and don't mean to be a nag but my team is doing a lot of a11y work right now and we have some excitement for working on this lib and enhancing it even more.  So if you have a moment to consider merging this and providing me permissions to be a maintainer, I'd really love to be able to do more with this great repo.

**Comment by wyattdanger** [comment]
@erin-doyle sorry i had been traveling and away from computers. i'll get to this this week, probably wednesday! y'all still have the interested in this?

**Comment by wyattdanger** [comment]
OK I have it checked out locally and passing all tests! Can you go ahead and give me a tldr for a changelog entry, and then I'll cut the release?

**Comment by wyattdanger** [comment]
Went ahead and sent y'all invites to maintain

**Comment by erin-doyle** [comment]
Yes I got the invite and we are definitely still interested, thanks @wyattdanger !

This is definitely semver major.  The API has changed completely.  So I can totally update this PR and then put together a release if you'd like.

**Comment by romeovs** [comment]
Good to see that this was merged! Thanks @erin-doyle and his team for putting in so much effort into this PR!

**Pull request merged**
