### PR TITLE
Fix for object.assign issue #115

### PR DESCRIPTION
**Pull request by vitkon**
### Problem ###
Currently there's an issue #115 open

### Fix ###
this fix doesn't require `object.assign` and uses spread operator intead to come up with new props.

### CODE REVIEW

**Comment by vitkon** [comment]
Another option will be to use native support for `Object.assign`

**Comment by ljharb** [comment]
The object spread operator is not standard yet, and is not a solution. Additionally, relying on native `Object.assign` support limits which engines/browsers this can be used. The proper fix is to add `object.assign` to "dependencies".

**Comment by wyattdanger** [comment]
Fixing with https://github.com/reactjs/react-a11y/pull/117

**Comment by vitkon** [comment]
@ljharb agreed

**Pull request closed without merging**
